[package]
name = "hello_world_rust"
version = "0.1.0"
authors = ["Eugene van der Merwe <eugenevdm@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.11.0"
#cairo = "0.0.4"
cairo-rs = { version = "0.2.0", features = ["png"] }